config/routes.rb
TrainingCrud::Application.routes.draw do
  resources :movies
  resources :users
  resources :rentas

end

app/models/movie.rb
class Movie < ActiveRecord::Base
  has_and_belongs_to_many :users
  accepts_nested_attributes_for :users
end

app/models/renta.rb
class Renta < ActiveRecord::Base
  belongs_to :user, :class_name => "User"
  belongs_to :movie, :class_name => "Movie"
end

app/models/user.rb
class User < ActiveRecord::Base
  before_create :record_available
  has_and_belongs_to_many :movies
  accepts_nested_attributes_for :movies

  def self.search(search)
    if search
      find(:all,:conditions => ['name LIKE ? or email LIKE ? and available = ?', "%#{search}%","%#{search}%",true])
    else
      find(:all,:conditions => ['available = ?',true])
    end
  end


  private

    def record_available
      self.available = true
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  # GET /movies
  # GET /movies.json
  def index
    @movies = Movie.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @movies }
    end
  end

  # GET /movies/1
  # GET /movies/1.json
  def show
    @movie = Movie.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @movie }
    end
  end

  # GET /movies/new
  # GET /movies/new.json
  def new
    @movie = Movie.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @movie }
    end
  end

  # GET /movies/1/edit
  def edit
    @movie = Movie.find(params[:id])
  end

  # POST /movies
  # POST /movies.json
  def create
    @movie = Movie.new(params[:movie])

    respond_to do |format|
      if @movie.save
        format.html { redirect_to @movie, notice: 'Movie was successfully created.' }
        format.json { render json: @movie, status: :created, location: @movie }
      else
        format.html { render action: "new" }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /movies/1
  # PUT /movies/1.json
  def update
    @movie = Movie.find(params[:id])

    respond_to do |format|
      if @movie.update_attributes(params[:movie])
        format.html { redirect_to @movie, notice: 'Movie was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /movies/1
  # DELETE /movies/1.json
  def destroy
    @movie = Movie.find(params[:id])
    @movie.destroy

    respond_to do |format|
      format.html { redirect_to movies_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/rentas_controller.rb
class RentasController < ApplicationController
  # GET /rentas
  # GET /rentas.json
  def index
    @rentas = Renta.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @rentas }
    end
  end

  # GET /rentas/1
  # GET /rentas/1.json
  def show
    @renta = Renta.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @renta }
    end
  end

  # GET /rentas/new
  # GET /rentas/new.json
  def new
    @renta = Renta.new
  end

  # GET /rentas/1/edit
  def edit
    @renta = Renta.find(params[:id])
  end

  # POST /rentas
  # POST /rentas.json
  def create
    @renta = Renta.new(params[:renta])

    respond_to do |format|
      if @renta.save
        format.html { redirect_to :action => 'index', notice: 'Renta was successfully created.' }
        format.json { render json: @renta, status: :created, location: @renta }
      else
        format.html { render action: "new" }
        format.json { render json: @renta.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /rentas/1
  # PUT /rentas/1.json
  def update
    @renta = Renta.find(params[:id])

    respond_to do |format|
      if @renta.update_attributes(params[:renta])
        format.html { redirect_to @renta, notice: 'Renta was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @renta.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rentas/1
  # DELETE /rentas/1.json
  def destroy
    @renta = Renta.find(params[:id])
    @renta.destroy

    respond_to do |format|
      format.html { redirect_to rentas_url }
      format.json { head :no_content }
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.search(params[:search])
  end

  def create
    if User.create(params[:user])
      redirect_to :action => :index
    else
      redirect_to :back 
    end
  end

  def new
    @user = User.new
  end

  def edit
    @user = User.find(params[:id])    
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user])
      flash[:notice] = 'User updated.'
      redirect_to :action => :index
    else
      flash[:error] = 'Couldn\'t update the user. Please check the errors.'
      redirect_to :back
    end    
  end

  def destroy
    @user = User.find(params[:id])
    if @user.update_attribute(:available,false)
      flash[:notice] = 'User deleted.'
      redirect_to :action => :index
    else
      flash[:error] = 'Couldn\'t delete the user. Please check the errors.'
      redirect_to :back
    end
  end

  def show
    @user = User.find(params[:id])
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/rentas_helper.rb
module RentasHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title TrainingCrud
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body
    = yield

app/views/layouts/search.html.haml
 - @users.results.try(:each) do |u|
   %span= link_to u.name, #

app/views/movies/_form.html.haml
= form_for @movie do |f|
  -if @movie.errors.any?
    #error_explanation
      %h2= "#{pluralize(@movie.errors.count, "error")} prohibited this movie from being saved:"
      %ul
        - @movie.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :author
    = f.text_field :author
  .actions
    = f.submit 'Save'

app/views/movies/edit.html.haml
%h1 Editing movie

= render 'form'

= link_to 'Show', @movie
\|
= link_to 'Back', movies_path

app/views/movies/index.html.haml
%h1 Listing movies

%table
  %tr
    %th Title
    %th Author
    %th
    %th
    %th

  - @movies.each do |movie|
    %tr
      %td= movie.title
      %td= movie.author
      %td= link_to 'Show', movie
      %td= link_to 'Edit', edit_movie_path(movie)
      %td= link_to 'Destroy', movie, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Movie', new_movie_path

app/views/movies/new.html.haml
%h1 New movie

= render 'form'

= link_to 'Back', movies_path

app/views/movies/show.html.haml
%p#notice= notice

%p
  %b Title:
  = @movie.title
%p
  %b Author:
  = @movie.author

= link_to 'Edit', edit_movie_path(@movie)
\|
= link_to 'Back', movies_path

app/views/rentas/_form.html.haml
= form_for @renta do |f|
  -if @renta.errors.any?
    #error_explanation
      %h2= "#{pluralize(@renta.errors.count, "error")} prohibited this renta from being saved:"
      %ul
        - @renta.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :user_id
    = f.text_field :user_id
  .field
    = f.label :movie_id
    = f.text_field :movie_id
  .actions
    = f.submit 'Save'

app/views/rentas/edit.html.haml
%h1 Editing renta

= render 'form'

= link_to 'Show', renta_path(@renta)
\|
= link_to 'Back', rentas_path

app/views/rentas/index.html.haml
%h1 Listing rentas

%table
  %tr
    %th User
    %th Movie
    %th
    %th
    %th

  - @rentas.each do |renta|
    %tr
      %td= "#{renta.user.name} #{renta.user.last_name}"
      %td= renta.movie.title
      %td= link_to 'Show', renta_path(renta)
      %td= link_to 'Edit', edit_renta_path(renta)
      %td= link_to 'Destroy', renta_path(renta), :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New renta', new_renta_path

app/views/rentas/new.html.haml
%h1 New renta

-#= render :partial => 'form', :locals => {:renta => @renta}
= form_for @renta, :url => {:action => "create"} do |f|
  -if @renta.errors.any?
    #error_explanation
      %h2= "#{pluralize(@renta.errors.count, "error")} prohibited this renta from being saved:"
      %ul
        - @renta.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :user_id
    = f.text_field :user_id
  .field
    = f.label :movie_id
    = f.text_field :movie_id
  .actions
    = f.submit 'Save'

= link_to 'Back', rentas_path

app/views/rentas/show.html.haml
%p#notice= notice

%p
  %b Movie title:
  = @renta.movie.title
%p
  %b User:
  = @renta.user.name

= link_to 'Edit', edit_renta_path(@renta)
\|
= link_to 'Back', rentas_path

app/views/users/_form.html.haml
= form_for @user do |f|
  = f.label :name
  = f.text_field :name

  = f.label :last_name
  = f.text_field :last_name

  = f.label :email
  = f.text_field :email

  = f.label :address
  = f.text_field :address

  -#= f.label :available
  -#= f.check_box :available

  = f.submit

app/views/users/_user.html.haml
= link_to user.name,user_path(user) 
= link_to "edit",edit_user_path(user)
= link_to "delete",user_path(user), :method => "delete"
%br

app/views/users/edit.html.haml
= render "form"

app/views/users/index.html.haml
%h2 Users
= render @users
= link_to "Create User", new_user_path

= form_tag users_path,  :method=>:get do
  =text_field_tag :search, params[:search]
  =submit_tag :search      

app/views/users/new.html.haml
= render "form"

app/views/users/show.html.haml
%h3 Name
=@user.name
%h3 Email
=@user.email
%br
=link_to "back",users_path